# Generated by Django 2.2.2 on 2019-06-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190623_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
