# Generated by Django 2.2.2 on 2019-06-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAdd', '0011_order'),
        ('user', '0004_auto_20190623_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, default=0, related_name='wishlist', to='productAdd.Product'),
        ),
    ]
