# Generated by Django 2.2.2 on 2019-06-24 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_profile_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wishlist',
        ),
    ]
