# Generated by Django 2.2.2 on 2019-06-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('bouqet_type', models.IntegerField(choices=[(1, 'bride'), ('2', 'groom')], default=1)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('flower_type', models.IntegerField(choices=[(1, 'Rose'), (2, 'Mixed Flower')], default=1)),
                ('image', models.ImageField(upload_to='product_pics')),
            ],
        ),
    ]
