# Generated by Django 2.2.2 on 2019-06-18 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAdd', '0002_auto_20190618_0628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
