# Generated by Django 2.2.2 on 2019-06-18 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAdd', '0003_auto_20190618_0633'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
