# Generated by Django 2.2.2 on 2019-06-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAdd', '0005_auto_20190618_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bouqet_type',
            field=models.IntegerField(choices=[(1, 'bride'), (2, 'groom')], default=1),
        ),
    ]
