# Generated by Django 2.2.2 on 2019-06-22 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAdd', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, default=0, related_name='cart', to='productAdd.Product'),
        ),
    ]
