# Generated by Django 2.2.2 on 2019-06-23 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productAdd', '0009_auto_20190622_0628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
