# Generated by Django 2.2.2 on 2019-06-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAdd', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
