# Generated by Django 2.2.2 on 2019-06-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAdd', '0017_auto_20190625_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=1000.0, max_digits=10),
            preserve_default=False,
        ),
    ]
