# Generated by Django 2.2.2 on 2019-06-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAdd', '0018_order_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_order',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
