# Generated by Django 2.2.2 on 2019-06-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productAdd', '0019_order_cancel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_order',
            field=models.CharField(max_length=100),
        ),
    ]
